package mybatis.dao;

import java.util.List;
import mybatis.model.Library;
import org.mybatis.cdi.Mapper;

@Mapper
public interface LibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Sun Apr 28 15:02:03 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Sun Apr 28 15:02:03 EEST 2024
     */
    int insert(Library record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Sun Apr 28 15:02:03 EEST 2024
     */
    Library selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Sun Apr 28 15:02:03 EEST 2024
     */
    List<Library> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Sun Apr 28 15:02:03 EEST 2024
     */
    int updateByPrimaryKey(Library record);
}